export const USER_LOGGED = "USER_LOGGED";
export const WAITING = "WAITING";
export const DONE_WAITING = "DONE_WAITING";
export const RETRIEVED_USER_INFO = "RETRIEVED_USER_INFO";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
